name: API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps  

      # ---------------- API TESTS ----------------
      - name: Run API tests
        run: npx playwright test 

      - name: Generate API Allure report
        run: |
          npx allure generate allure-results/api -o allure-report/api --clean

      # (opcional) guardar artefacto si querés
      - name: Upload API Allure artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-report
          path: allure-report/api
