name: API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps  

      # ---------------- API TESTS ----------------
      - name: Run API tests
<<<<<<< HEAD
        run: |
          export ALLURE_RESULTS_DIR=allure-results/api
          npx playwright test --project=ui
=======
        run: npx playwright test --project=api
>>>>>>> b04db4ebf14716cf63420e630494761f8dc0d68c

      - name: Generate API Allure report
        run: |
          npx allure generate allure-results/api -o allure-report/api --clean

      - name: Publish API report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          destination_dir: api
          publish_dir: allure-report/api
